# Site settings
author: Jack W. Goode
title: My Coding Journey with Flatiron Bootcamp
header-img: img/home-bg.png
email: jack.w.goode@icloud.com
copyright_name: Jack W. Goode
description: > # this means to ignore newlines until "baseurl:"
  My Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jack-wgoode

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
